services:
    app:
        build:
            context: .
            target: serve
        ports:
            - ${APP_PORT}
        volumes:
            - ./src:/app/src
            - ./build:/app/build
        depends_on:
            mysql:
                condition: service_healthy
    mysql:
        image: mysql
        ports:
            - ${DB_PORT}
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes: 
            - /var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
        cap_add:
            - SYS_NICE